/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'product-categories': ProductCategory;
    news: News;
    pages: Page;
    'contact-submissions': ContactSubmission;
    'newsletter-subscribers': NewsletterSubscriber;
    languages: Language;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    languages: LanguagesSelect<false> | LanguagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'de') | ('en' | 'de')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
    'homepage-settings': HomepageSetting;
    'about-page-settings': AboutPageSetting;
    'contact-page-settings': ContactPageSetting;
    'news-page-settings': NewsPageSetting;
    'our-business-page-settings': OurBusinessPageSetting;
    'ui-labels': UiLabel;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'homepage-settings': HomepageSettingsSelect<false> | HomepageSettingsSelect<true>;
    'about-page-settings': AboutPageSettingsSelect<false> | AboutPageSettingsSelect<true>;
    'contact-page-settings': ContactPageSettingsSelect<false> | ContactPageSettingsSelect<true>;
    'news-page-settings': NewsPageSettingsSelect<false> | NewsPageSettingsSelect<true>;
    'our-business-page-settings': OurBusinessPageSettingsSelect<false> | OurBusinessPageSettingsSelect<true>;
    'ui-labels': UiLabelsSelect<false> | UiLabelsSelect<true>;
  };
  locale: 'en' | 'de';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Manage admin and editor accounts
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Images, documents and files
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility & SEO
   */
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Mould product categories
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  /**
   * Product name (e.g. PPR-C Sanitary Fittings Moulds)
   */
  name: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  featuredImage?: (number | null) | Media;
  /**
   * Raw material type (e.g. PPR-C, HDPE)
   */
  materials?: string | null;
  /**
   * Key features and technologies
   */
  technologies?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  brochure?: (number | null) | Media;
  /**
   * Display order (lower = first)
   */
  sortOrder?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * News articles and exhibition events
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  slug: string;
  featuredImage?: (number | null) | Media;
  /**
   * Short summary shown in listing cards
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  date: string;
  /**
   * Year badge shown on card
   */
  year?: string | null;
  status?: ('draft' | 'published') | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Dynamic pages with block-based page builder
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  heroType?: ('banner' | 'slider' | 'none') | null;
  heroTitle?: string | null;
  heroImage?: (number | null) | Media;
  layout?:
    | (
        | {
            slides?:
              | {
                  title: string;
                  subtitle?: string | null;
                  backgroundImage: number | Media;
                  ctaLabel?: string | null;
                  ctaLink?: string | null;
                  overlayOpacity?: number | null;
                  textAlignment?: ('left' | 'center' | 'right') | null;
                  textPosition?: ('top' | 'center' | 'bottom') | null;
                  titleSize?: ('small' | 'medium' | 'large') | null;
                  animateText?: boolean | null;
                  textAnimation?: ('fadeUp' | 'fadeIn' | 'slideLeft' | 'slideRight') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroSlider';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            title?: string | null;
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            columns?: ('2' | '3' | '4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageGallery';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            products?: (number | ProductCategory)[] | null;
            /**
             * Max products to show. Leave empty to show selected products.
             */
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productGrid';
          }
        | {
            title?: string | null;
            description?: string | null;
            showMap?: boolean | null;
            mapEmbedUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
        | {
            title?: string | null;
            /**
             * YouTube or Vimeo URL
             */
            videoUrl: string;
            thumbnailImage?: (number | null) | Media;
            sideImages?:
              | {
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoEmbed';
          }
        | {
            title?: string | null;
            description?: string | null;
            values?:
              | {
                  /**
                   * Icon name or emoji
                   */
                  icon?: string | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'coreValues';
          }
        | {
            title?: string | null;
            certificates?:
              | {
                  name: string;
                  image: number | Media;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'certificatesGrid';
          }
        | {
            text: string;
            buttonLabel: string;
            buttonLink: string;
            style?: ('red' | 'navy' | 'cyan') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBar';
          }
        | {
            leftColumn: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            rightColumn: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            image?: (number | null) | Media;
            imagePosition?: ('left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoColumnContent';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Incoming contact form submissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  subject?: string | null;
  message: string;
  readStatus?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Newsletter email list
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  name?: string | null;
  email: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Only English (en) and German (de) are supported. Changes require a server restart.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "languages".
 */
export interface Language {
  id: number;
  /**
   * ISO 639-1 language code (e.g. en, de). Only EN and DE are supported.
   */
  code: string;
  label: string;
  /**
   * Language name in its own language (e.g. Deutsch)
   */
  nativeLabel: string;
  /**
   * Short label for language selector (e.g. EN, DE)
   */
  shortLabel: string;
  /**
   * Set as the default language. Only one language can be default.
   */
  isDefault?: boolean | null;
  /**
   * Only active languages are shown on the website.
   */
  isActive?: boolean | null;
  /**
   * Enable for right-to-left languages (e.g. Arabic, Hebrew).
   */
  isRTL?: boolean | null;
  /**
   * Flag emoji for the language (e.g. 🇬🇧, 🇩🇪). Optional.
   */
  flagEmoji?: string | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'languages';
        value: number | Language;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  featuredImage?: T;
  materials?: T;
  technologies?:
    | T
    | {
        item?: T;
        id?: T;
      };
  description?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  brochure?: T;
  sortOrder?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featuredImage?: T;
  excerpt?: T;
  content?: T;
  date?: T;
  year?: T;
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroType?: T;
  heroTitle?: T;
  heroImage?: T;
  layout?:
    | T
    | {
        heroSlider?:
          | T
          | {
              slides?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    backgroundImage?: T;
                    ctaLabel?: T;
                    ctaLink?: T;
                    overlayOpacity?: T;
                    textAlignment?: T;
                    textPosition?: T;
                    titleSize?: T;
                    animateText?: T;
                    textAnimation?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        imageGallery?:
          | T
          | {
              title?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              columns?: T;
              id?: T;
              blockName?: T;
            };
        productGrid?:
          | T
          | {
              title?: T;
              subtitle?: T;
              products?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              title?: T;
              description?: T;
              showMap?: T;
              mapEmbedUrl?: T;
              id?: T;
              blockName?: T;
            };
        videoEmbed?:
          | T
          | {
              title?: T;
              videoUrl?: T;
              thumbnailImage?: T;
              sideImages?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        coreValues?:
          | T
          | {
              title?: T;
              description?: T;
              values?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        certificatesGrid?:
          | T
          | {
              title?: T;
              certificates?:
                | T
                | {
                    name?: T;
                    image?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBar?:
          | T
          | {
              text?: T;
              buttonLabel?: T;
              buttonLink?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
        twoColumnContent?:
          | T
          | {
              leftColumn?: T;
              rightColumn?: T;
              image?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  readStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "languages_select".
 */
export interface LanguagesSelect<T extends boolean = true> {
  code?: T;
  label?: T;
  nativeLabel?: T;
  shortLabel?: T;
  isDefault?: T;
  isActive?: T;
  isRTL?: T;
  flagEmoji?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * General site configuration, contact info, and integrations
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  logo?: (number | null) | Media;
  logoWhite?: (number | null) | Media;
  defaultSeoDescription?: string | null;
  contact?: {
    email?: string | null;
    phone?: string | null;
    fax?: string | null;
    whatsapp?: string | null;
    address?: string | null;
    /**
     * Paste the Google Maps iframe src URL
     */
    googleMapsEmbed?: string | null;
    /**
     * Used in LocalBusiness JSON-LD schema. Add one entry per day range.
     */
    openingHours?:
      | {
          dayOfWeek: 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday';
          /**
           * e.g. "09:00"
           */
          opens?: string | null;
          /**
           * e.g. "18:00"
           */
          closes?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Displayed in LocalBusiness schema — e.g. "$" means budget, "$$$" means premium
     */
    priceRange?: ('$' | '$$' | '$$$' | '$$$$') | null;
    /**
     * Contact + newsletter submissions are emailed here. If empty, the Contact email above is used.
     */
    notificationEmail?: string | null;
  };
  socialMedia?: {
    facebook?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    linkedin?: string | null;
    twitter?: string | null;
  };
  chatbot?: {
    enabled?: boolean | null;
    /**
     * Override the default chatbot behavior (optional)
     */
    systemPrompt?: string | null;
    labels?: {
      /**
       * "Polinar AI" or chat title
       */
      title?: string | null;
      /**
       * Welcome message
       */
      welcome?: string | null;
      /**
       * Input placeholder
       */
      placeholder?: string | null;
      /**
       * "Chat on WhatsApp"
       */
      whatsappLabel?: string | null;
      /**
       * "Close" aria-label
       */
      closeLabel?: string | null;
      /**
       * Generic error
       */
      errorMessage?: string | null;
      /**
       * Connection error
       */
      connectionError?: string | null;
    };
  };
  whatsappCTA?: {
    enabled?: boolean | null;
    text?: string | null;
  };
  /**
   * Adds FAQPage JSON-LD schema for Google rich results. Leave empty to disable.
   */
  faq?: {
    items?:
      | {
          /**
           * The question
           */
          question: string;
          /**
           * The answer text
           */
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Google Search Console, IndexNow, and search engine settings
   */
  googleIntegration?: {
    /**
     * HTML meta tag content from Google Search Console. Found in GSC → Settings → Verification method → HTML meta tag.
     */
    gscVerificationToken?: string | null;
    indexNow?: {
      /**
       * Get your key from https://www.indexnow.org — leave empty to disable IndexNow
       */
      apiKey?: string | null;
      /**
       * When enabled, page changes are submitted to Bing and Google via IndexNow protocol
       */
      enabled?: boolean | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure header menu and mega menu structure
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  mainMenu?:
    | {
        label: string;
        type?: ('link' | 'mega') | null;
        /**
         * Path like /products or full URL
         */
        url?: string | null;
        megaMenuColumns?:
          | {
              columnTitle?: string | null;
              columnType?: ('links' | 'featuredProducts' | 'imageCard') | null;
              links?:
                | {
                    label: string;
                    url: string;
                    /**
                     * Short description shown in homepage cards and mega menu
                     */
                    description?: string | null;
                    /**
                     * Icon shown in homepage card and mega menu
                     */
                    icon?: ('moulds' | 'machinery' | 'testing') | null;
                    /**
                     * Optional image for homepage card background
                     */
                    image?: (number | null) | Media;
                    id?: string | null;
                  }[]
                | null;
              featuredProducts?: (number | ProductCategory)[] | null;
              image?: (number | null) | Media;
              imageCaption?: string | null;
              imageLink?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The "Get in Touch" call-to-action shown in mega menu overlays
   */
  megaMenuCTA?: {
    /**
     * "Get in Touch" / "Bize Ulaşın"
     */
    title?: string | null;
    /**
     * CTA description text
     */
    description?: string | null;
    /**
     * "Contact Us" / "İletişim"
     */
    button?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Footer content and newsletter settings
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  labels?: {
    /**
     * "Address" / "Adres"
     */
    addressLabel?: string | null;
    /**
     * "Phone / Fax" / "Telefon / Faks"
     */
    phoneFaxLabel?: string | null;
    /**
     * "E-mail"
     */
    emailLabel?: string | null;
    /**
     * "Newsletter" / "Bülten"
     */
    newsletterLabel?: string | null;
    /**
     * "Subscribe" / "Abone Ol"
     */
    subscribeButton?: string | null;
    /**
     * "Your Name" / "Adınız"
     */
    namePlaceholder?: string | null;
    /**
     * "Your Email" / "E-postanız"
     */
    emailPlaceholder?: string | null;
  };
  /**
   * e.g. Copyright © 2024 All Rights Reserved by Polinar
   */
  copyrightText?: string | null;
  columns?:
    | {
        title?: string | null;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  showNewsletter?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Homepage hero, values, featured content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-settings".
 */
export interface HomepageSetting {
  id: number;
  /**
   * Search engine optimization settings. Leave blank to auto-generate from page content.
   */
  seo?: {
    /**
     * Override the page title in search results. Max ~60 characters recommended.
     */
    title?: string | null;
    /**
     * Override the page description in search results. Max ~160 characters recommended.
     */
    description?: string | null;
    /**
     * Override the Open Graph / social sharing image. Recommended: 1200×630px.
     */
    image?: (number | null) | Media;
  };
  /**
   * Global slider behavior and appearance settings
   */
  sliderSettings?: {
    autoPlay?: boolean | null;
    pauseOnHover?: boolean | null;
    showArrows?: boolean | null;
    showDots?: boolean | null;
    /**
     * Time between slides (1000-15000ms)
     */
    interval?: number | null;
    /**
     * Animation duration (200-3000ms)
     */
    transitionDuration?: number | null;
    transitionType?: ('fade' | 'slide' | 'zoom' | 'slideUp') | null;
  };
  heroSlides?:
    | {
        title: string;
        subtitle?: string | null;
        backgroundImage?: (number | null) | Media;
        ctaLabel?: string | null;
        ctaLink?: string | null;
        /**
         * 0 = transparent, 100 = fully dark
         */
        overlayOpacity?: number | null;
        textAlignment?: ('left' | 'center' | 'right') | null;
        textPosition?: ('top' | 'center' | 'bottom') | null;
        titleSize?: ('small' | 'medium' | 'large') | null;
        animateText?: boolean | null;
        textAnimation?: ('fadeUp' | 'fadeIn' | 'slideLeft' | 'slideRight') | null;
        id?: string | null;
      }[]
    | null;
  coreValues?: {
    /**
     * e.g. Quality / Robust / Durable / Reliable
     */
    title?: string | null;
    description?: string | null;
  };
  aboutPreview?: {
    text?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image?: (number | null) | Media;
  };
  /**
   * Select products to feature on homepage
   */
  featuredProducts?: (number | ProductCategory)[] | null;
  promotionVideo?: {
    /**
     * YouTube or Vimeo URL
     */
    videoUrl?: string | null;
    thumbnailImage?: (number | null) | Media;
    sideImages?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  aboutPreviewLabels?: {
    /**
     * "About" / "Hakkımızda"
     */
    label?: string | null;
    /**
     * "US" / ""
     */
    title?: string | null;
    /**
     * Short about preview paragraph
     */
    description?: string | null;
    /**
     * Large image in the right column of the homepage About block (not the faint watermark — use About Preview Decoration for that).
     */
    image?: (number | null) | Media;
  };
  /**
   * Background artwork for the About Preview block (optional).
   */
  aboutPreviewDecor?: {
    /**
     * Large faint image behind the text column on desktop. Uses a default if empty.
     */
    leftWatermark?: (number | null) | Media;
  };
  businessSection?: {
    /**
     * e.g. Faaliyetlerimiz / Our Business
     */
    sectionLabel?: string | null;
    /**
     * e.g. Ne Yapıyoruz? / What We Do
     */
    sectionTitle?: string | null;
  };
  newsSection?: {
    /**
     * "Latest News" / "Son Haberler"
     */
    label?: string | null;
    /**
     * "Fair Agenda" / "Fuar Gündemi"
     */
    title?: string | null;
    /**
     * "News coming soon" / "Haberler yakında eklenecek"
     */
    empty?: string | null;
  };
  /**
   * Select up to 3 news items for homepage
   */
  featuredNews?: (number | News)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Full About page content: hero, company story, statistics, gallery, video, certificates, CTA
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page-settings".
 */
export interface AboutPageSetting {
  id: number;
  /**
   * Search engine optimization settings. Leave blank to auto-generate from page content.
   */
  seo?: {
    /**
     * Override the page title in search results. Max ~60 characters recommended.
     */
    title?: string | null;
    /**
     * Override the page description in search results. Max ~160 characters recommended.
     */
    description?: string | null;
    /**
     * Override the Open Graph / social sharing image. Recommended: 1200×630px.
     */
    image?: (number | null) | Media;
  };
  hero?: {
    /**
     * Small label above title — e.g. "About"
     */
    label?: string | null;
    /**
     * Main hero H1 — e.g. "ABOUT US"
     */
    title?: string | null;
    /**
     * Subtitle below main title
     */
    subtitle?: string | null;
    /**
     * Full-width hero background image
     */
    backgroundImage?: (number | null) | Media;
  };
  story?: {
    /**
     * e.g. "About Polinar"
     */
    title?: string | null;
    /**
     * Year badge — e.g. "2000"
     */
    foundedYear?: string | null;
    paragraph1?: string | null;
    paragraph2?: string | null;
    paragraph3?: string | null;
    /**
     * Large primary image
     */
    mainImage?: (number | null) | Media;
    /**
     * Small floating overlay image
     */
    accentImage?: (number | null) | Media;
    /**
     * Button text — e.g. "Contact Us"
     */
    ctaText?: string | null;
    /**
     * Button link — e.g. "/contact"
     */
    ctaLink?: string | null;
  };
  statistics?: {
    cards?:
      | {
          /**
           * Numeric value — e.g. 2000
           */
          number: number;
          /**
           * Suffix after number — e.g. "+"
           */
          suffix?: string | null;
          /**
           * Description — e.g. "Years of Experience"
           */
          label: string;
          /**
           * Emoji or icon — e.g. "🏭"
           */
          icon?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  gallery?: {
    /**
     * e.g. "Photos from Production Area"
     */
    title?: string | null;
    description?: string | null;
    images?:
      | {
          image: number | Media;
          caption?: string | null;
          size?: ('normal' | 'large') | null;
          id?: string | null;
        }[]
      | null;
  };
  video: {
    /**
     * e.g. "Our Promotion Video"
     */
    title?: string | null;
    description?: string | null;
    /**
     * YouTube or Vimeo URL
     */
    videoUrl: string;
    /**
     * Poster/thumbnail image shown before play
     */
    thumbnailImage?: (number | null) | Media;
    /**
     * Video publish date (YYYY-MM-DD) — used in VideoObject schema
     */
    uploadDate?: string | null;
  };
  /**
   * Adds FAQPage JSON-LD schema for Google rich results. Leave empty to disable.
   */
  faq?: {
    items?:
      | {
          /**
           * The question — e.g. "What materials do you work with?"
           */
          question: string;
          /**
           * The answer text
           */
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  certificates?: {
    /**
     * e.g. "Our Certificates"
     */
    title?: string | null;
    /**
     * Intro paragraph about quality standards
     */
    description?: string | null;
    items?:
      | {
          /**
           * e.g. "ISO 9001"
           */
          name: string;
          image: number | Media;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    /**
     * e.g. "Need Detailed Information?"
     */
    title?: string | null;
    description?: string | null;
    /**
     * e.g. "Contact via WhatsApp"
     */
    buttonText?: string | null;
    /**
     * e.g. WhatsApp URL
     */
    buttonLink?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Contact page hero, form labels, and success/error messages
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page-settings".
 */
export interface ContactPageSetting {
  id: number;
  /**
   * Search engine optimization settings. Leave blank to auto-generate from page content.
   */
  seo?: {
    /**
     * Override the page title in search results. Max ~60 characters recommended.
     */
    title?: string | null;
    /**
     * Override the page description in search results. Max ~160 characters recommended.
     */
    description?: string | null;
    /**
     * Override the Open Graph / social sharing image. Recommended: 1200×630px.
     */
    image?: (number | null) | Media;
  };
  hero?: {
    /**
     * e.g. "Contact Us"
     */
    title?: string | null;
    /**
     * e.g. "Get in touch with our team"
     */
    subtitle?: string | null;
  };
  form?: {
    nameLabel?: string | null;
    emailLabel?: string | null;
    subjectLabel?: string | null;
    messageLabel?: string | null;
    sendButton?: string | null;
    sendingButton?: string | null;
  };
  messages?: {
    /**
     * Shown after successful submit
     */
    success?: string | null;
    /**
     * Shown on submit failure
     */
    error?: string | null;
  };
  /**
   * Labels shown next to actual contact details from Site Settings
   */
  info?: {
    addressLabel?: string | null;
    /**
     * Optional. If Site Settings → Contact → Address is set, that value is shown instead.
     */
    addressText?: string | null;
    phoneLabel?: string | null;
    emailLabel?: string | null;
  };
  /**
   * Newsletter subscription form labels shown in the footer
   */
  newsletter?: {
    title?: string | null;
    description?: string | null;
    namePlaceholder?: string | null;
    emailPlaceholder?: string | null;
    submitButton?: string | null;
    successMessage?: string | null;
    errorMessage?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * News listing hero, breadcrumb labels, and empty-state text
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-page-settings".
 */
export interface NewsPageSetting {
  id: number;
  /**
   * Search engine optimization settings. Leave blank to auto-generate from page content.
   */
  seo?: {
    /**
     * Override the page title in search results. Max ~60 characters recommended.
     */
    title?: string | null;
    /**
     * Override the page description in search results. Max ~160 characters recommended.
     */
    description?: string | null;
    /**
     * Override the Open Graph / social sharing image. Recommended: 1200×630px.
     */
    image?: (number | null) | Media;
  };
  hero?: {
    /**
     * Small label — e.g. "Latest Updates"
     */
    label?: string | null;
    /**
     * Main title — e.g. "NEWS & EXHIBITIONS"
     */
    title?: string | null;
    image?: (number | null) | Media;
  };
  labels?: {
    /**
     * Shown when no news articles exist
     */
    empty?: string | null;
    /**
     * Breadcrumb text — e.g. "News"
     */
    breadcrumb?: string | null;
    /**
     * Back button — e.g. "All News"
     */
    allNews?: string | null;
    /**
     * Placeholder when article has no CMS content yet
     */
    cmsPlaceholder?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Our Business landing page SEO settings
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-business-page-settings".
 */
export interface OurBusinessPageSetting {
  id: number;
  /**
   * Search engine optimization settings. Leave blank to auto-generate from page content.
   */
  seo?: {
    /**
     * Override the page title in search results. Max ~60 characters recommended.
     */
    title?: string | null;
    /**
     * Override the page description in search results. Max ~160 characters recommended.
     */
    description?: string | null;
    /**
     * Override the Open Graph / social sharing image. Recommended: 1200×630px.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Shared micro-copy used across multiple pages (e.g. "Learn More", "Read More")
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ui-labels".
 */
export interface UiLabel {
  id: number;
  /**
   * "Learn More" / "Detaylar"
   */
  learnMore?: string | null;
  /**
   * "Read More" / "Devamını Oku"
   */
  readMore?: string | null;
  /**
   * "Content coming soon." / "İçerik yakında eklenecektir."
   */
  contentComingSoon?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  logoWhite?: T;
  defaultSeoDescription?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        fax?: T;
        whatsapp?: T;
        address?: T;
        googleMapsEmbed?: T;
        openingHours?:
          | T
          | {
              dayOfWeek?: T;
              opens?: T;
              closes?: T;
              id?: T;
            };
        priceRange?: T;
        notificationEmail?: T;
      };
  socialMedia?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        youtube?: T;
        linkedin?: T;
        twitter?: T;
      };
  chatbot?:
    | T
    | {
        enabled?: T;
        systemPrompt?: T;
        labels?:
          | T
          | {
              title?: T;
              welcome?: T;
              placeholder?: T;
              whatsappLabel?: T;
              closeLabel?: T;
              errorMessage?: T;
              connectionError?: T;
            };
      };
  whatsappCTA?:
    | T
    | {
        enabled?: T;
        text?: T;
      };
  faq?:
    | T
    | {
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  googleIntegration?:
    | T
    | {
        gscVerificationToken?: T;
        indexNow?:
          | T
          | {
              apiKey?: T;
              enabled?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainMenu?:
    | T
    | {
        label?: T;
        type?: T;
        url?: T;
        megaMenuColumns?:
          | T
          | {
              columnTitle?: T;
              columnType?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    description?: T;
                    icon?: T;
                    image?: T;
                    id?: T;
                  };
              featuredProducts?: T;
              image?: T;
              imageCaption?: T;
              imageLink?: T;
              id?: T;
            };
        id?: T;
      };
  megaMenuCTA?:
    | T
    | {
        title?: T;
        description?: T;
        button?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  labels?:
    | T
    | {
        addressLabel?: T;
        phoneFaxLabel?: T;
        emailLabel?: T;
        newsletterLabel?: T;
        subscribeButton?: T;
        namePlaceholder?: T;
        emailPlaceholder?: T;
      };
  copyrightText?: T;
  columns?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  showNewsletter?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-settings_select".
 */
export interface HomepageSettingsSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  sliderSettings?:
    | T
    | {
        autoPlay?: T;
        pauseOnHover?: T;
        showArrows?: T;
        showDots?: T;
        interval?: T;
        transitionDuration?: T;
        transitionType?: T;
      };
  heroSlides?:
    | T
    | {
        title?: T;
        subtitle?: T;
        backgroundImage?: T;
        ctaLabel?: T;
        ctaLink?: T;
        overlayOpacity?: T;
        textAlignment?: T;
        textPosition?: T;
        titleSize?: T;
        animateText?: T;
        textAnimation?: T;
        id?: T;
      };
  coreValues?:
    | T
    | {
        title?: T;
        description?: T;
      };
  aboutPreview?:
    | T
    | {
        text?: T;
        image?: T;
      };
  featuredProducts?: T;
  promotionVideo?:
    | T
    | {
        videoUrl?: T;
        thumbnailImage?: T;
        sideImages?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  aboutPreviewLabels?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
        image?: T;
      };
  aboutPreviewDecor?:
    | T
    | {
        leftWatermark?: T;
      };
  businessSection?:
    | T
    | {
        sectionLabel?: T;
        sectionTitle?: T;
      };
  newsSection?:
    | T
    | {
        label?: T;
        title?: T;
        empty?: T;
      };
  featuredNews?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page-settings_select".
 */
export interface AboutPageSettingsSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  hero?:
    | T
    | {
        label?: T;
        title?: T;
        subtitle?: T;
        backgroundImage?: T;
      };
  story?:
    | T
    | {
        title?: T;
        foundedYear?: T;
        paragraph1?: T;
        paragraph2?: T;
        paragraph3?: T;
        mainImage?: T;
        accentImage?: T;
        ctaText?: T;
        ctaLink?: T;
      };
  statistics?:
    | T
    | {
        cards?:
          | T
          | {
              number?: T;
              suffix?: T;
              label?: T;
              icon?: T;
              id?: T;
            };
      };
  gallery?:
    | T
    | {
        title?: T;
        description?: T;
        images?:
          | T
          | {
              image?: T;
              caption?: T;
              size?: T;
              id?: T;
            };
      };
  video?:
    | T
    | {
        title?: T;
        description?: T;
        videoUrl?: T;
        thumbnailImage?: T;
        uploadDate?: T;
      };
  faq?:
    | T
    | {
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  certificates?:
    | T
    | {
        title?: T;
        description?: T;
        items?:
          | T
          | {
              name?: T;
              image?: T;
              description?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        title?: T;
        description?: T;
        buttonText?: T;
        buttonLink?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page-settings_select".
 */
export interface ContactPageSettingsSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  form?:
    | T
    | {
        nameLabel?: T;
        emailLabel?: T;
        subjectLabel?: T;
        messageLabel?: T;
        sendButton?: T;
        sendingButton?: T;
      };
  messages?:
    | T
    | {
        success?: T;
        error?: T;
      };
  info?:
    | T
    | {
        addressLabel?: T;
        addressText?: T;
        phoneLabel?: T;
        emailLabel?: T;
      };
  newsletter?:
    | T
    | {
        title?: T;
        description?: T;
        namePlaceholder?: T;
        emailPlaceholder?: T;
        submitButton?: T;
        successMessage?: T;
        errorMessage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-page-settings_select".
 */
export interface NewsPageSettingsSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  hero?:
    | T
    | {
        label?: T;
        title?: T;
        image?: T;
      };
  labels?:
    | T
    | {
        empty?: T;
        breadcrumb?: T;
        allNews?: T;
        cmsPlaceholder?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-business-page-settings_select".
 */
export interface OurBusinessPageSettingsSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ui-labels_select".
 */
export interface UiLabelsSelect<T extends boolean = true> {
  learnMore?: T;
  readMore?: T;
  contentComingSoon?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}